Using libsumo instead of TraCI
eclipse/mosaic pull request #27
Opened 2021-01-08 15:17 UTC by kschrab

## Type of this PR 

- [ ] Bug fix
- [x] Enhancement

## Description

This PR introduces a new way to couple SUMO with MOSAIC. Instead of the socket interface TraCI, a direct JNI binding called "libsumo" is used, making the coupling much faster. For now, both coupling methods are implemented in parallel, having TraCI coupling still as the default and preferred method. Using Libsumo currently comes with following issues:
 * SUMO-GUI cannot be used
 * Traffic light programs cannot be read out. The Libsumo method `TrafficLight.getAllProgramLogics(String)` currently returns an empty list in any case.
 * Controlled links of traffic lights cannot be read out yet.
 * Leader information cannot be read out yet.
 * Data read from induction loops is not complete

### Usage

The Libsumo coupling is chosen by using `LibSumoAmbassador` instead of `SumoAmbassador` in the `runtime.json` file. 

### Implementation 

Already in the previous state, all supported TraCI commands were placed in separate classes, such as `VehicleSetSpeed` or `SimulationSimulateStep`. The same has been done for the Libsumo commands. For each command, an interface class has been added, and one implementing class for each variant, located in different packages each:

* Interfaces within `api` package, e.g.  `org.eclipse.sumo.bridge.api.VehicleAdd`
* TraCI implementations in `traci` package, e.g.  `org.eclipse.sumo.bridge.traci.VehicleAdd`
* LibSumo implementations in `libsumo` package, e.g.  `org.eclipse.sumo.bridge.traci.VehicleAdd`

The several facades which contain the actual business logic do _not_ know which implementation is currently active. They just work with the command interfaces from the `api` package. The `CommandRegister` chooses between the `traci` or `libsumo` command implementations depending on what's configured. The `TraciClient` interface has been renamed to `Bridge` to have a more general name.

### Tests

Currently there's one integration test using the new Libsumo implementation (`BarnimLibsumoIT`).                 

## Issue(s) related to this PR

 * Internal issue 32 
 
## Affected parts of the online documentation

The developer-documentation in https://www.eclipse.org/mosaic/docs/extending_mosaic/sumo_ambassador_details/ needs to be updated accordingly, once this PR is accepted.

## Definition of Done

- [x] You have read CONTRIBUTING.md carefully.
- [x] You have signed the [Contributor License Agreement](http://www.eclipse.org/legal/CLA.php).
- [x] All commits are signed-off (`-s`) with your mail address of your Eclipse Account.
- [x] `origin/main` has been merged into your Fork.
- [x] New functionality is covered by unit tests or integration tests. Code coverage must not decrease.
- [ ] There are no new SpotBugs warnings. 
- [x] Coding guidelines have been observed (see CONTRIBUTING.md).
- [ ] All tests pass.

## Special notes to reviewer

2021-01-11 08:52 UTC, kschrab commented
- [ ] Open issue: SUMO installation in Docker image used for CI does not include libsumojni.so

2021-05-11 09:38 UTC, kschrab commented
@schwepmo please review

2021-05-28 12:38 UTC, schwepmo requested changes
* General points regarding SUMO api commands
    * parameter names should be unified
    * docs should be unified, probably one doc in the interfaces is fine
    * usage of `@Overload` shoud be unified
* documentation should be adjusted

2021-05-28 14:12 UTC, kschrab commented
All changes moved to a new PR (#114) due to check conflicts (presumably wrong author information due to a merge)

2021-05-28 14:13 UTC, closed without merging

2021-05-28 14:14 UTC, kschrab commented on pom.xml
> +        <version.libsumo>1.10.0-SNAPSHOT</version.libsumo>
I changed this now.

2021-05-28 14:14 UTC, kschrab commented on fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/libsumo/VehicleGetLeader.java
> +        //TODO currently not implemented on libsumo side
I added log.warn

2021-05-28 14:14 UTC, kschrab commented on fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/LibSumoBridge.java
> +        parameters.forEach(s::add);
actually even `new StringVector(parameters)` work :)

2021-05-28 14:15 UTC, kschrab commented on fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/libsumo/VehicleSetReactionTime.java
> +        implements org.eclipse.mosaic.fed.sumo.bridge.api.VehicleSetReactionTime {
I guess it would exceed max line length 💀

2021-05-28 14:16 UTC, kschrab commented on fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/libsumo/VehicleSetLaneChangeMode.java
> +    @Override
I removed all unnecessary occurrences of `@Override`