feat(app): Provide group value defined in mapping in applications
eclipse/mosaic pull request #285
Opened 2023-01-20 10:57 UTC by FunKuchen

## Type of this PR 

- Enhancement

## Description

Provide getGroup Method in OperatingSystem Interface and AbstractSimulationUnit. Adds a setGroup Method in AbstractSimulationUnit which is used to set the group value read from UnitRegistration message for each simulation object added to the simulation. This happens in each registerUnit method in the UnitSimulator class. That way one can access the group value in any application.

What is this PR about?

## Issue(s) related to this PR

Internal issue 284
  
## Affected parts of the online documentation

--
Changes in the documentation required?

## Definition of Done

- [ ] You have read CONTRIBUTING.md carefully.
- [ ] You have signed the [Contributor License Agreement](http://www.eclipse.org/legal/CLA.php).
- [ ] Your GitHub user id is linked with your Eclipse Account.
- [ ] `origin/main` has been merged into your Fork.
- [ ] New functionality is covered by unit tests or integration tests. Code coverage must not decrease.
- [ ] There are no new SpotBugs warnings. 
- [ ] Coding guidelines have been followed (see CONTRIBUTING.md).
- [ ] All tests pass.

## Special notes to reviewer

2023-01-20 11:14 UTC, kschrab requested changes
everything fine, still missing documentation of API method

2023-01-20 11:14 UTC, kschrab commented on fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/os/OperatingSystem.java
> +    String getGroup();
add javadoc

2023-01-20 11:14 UTC, FunKuchen commented
Is everything correct now?

2023-01-20 11:15 UTC, FunKuchen commented on fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/os/OperatingSystem.java
> +    String getGroup();
Alright, will do.

2023-01-20 12:25 UTC, kschrab commented on fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/os/OperatingSystem.java
> +
remove this empty line and we're good :)

2023-01-25 13:29 UTC, kschrab approved these changes

2023-01-25 13:29 UTC, merged