861 extend license check
eclipse/mosaic pull request #396
Opened 2024-07-24 08:25 UTC by kschrab

## Description

* This extends the JavaFederateExecutor to be able to pass JVM options.
* Furthermore, the RTI initialization now creates the `ComponentProvider` _before_ building the `FederateExecutors`.

## Issue(s) related to this PR

* Part of internal issue 861
  
## Affected parts of the online documentation

Changes in the documentation required?

No

## Definition of Done

**Prerequisites**

- [x] You have read CONTRIBUTING.md carefully.
- [x] You have signed the [Contributor License Agreement](http://www.eclipse.org/legal/CLA.php).
- [x] Your GitHub user id is linked with your Eclipse Account.

**Required**

- [x] The title of this merge request follows the scheme `type(scope): description`  (in the style of [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary))
- [ ] You have assigned a suitable label to this pull request (e.g., `enhancement`, or `bugfix`)
- [x] `origin/main` has been merged into your Fork.
- [x] Coding guidelines have been followed (see CONTRIBUTING.md).
- [ ] All checks on GitHub pass.
- [ ] All tests on [Jenkins](https://ci.eclipse.org/mosaic/job/mosaic/) pass.

**Requested** (can be enforced by maintainers)

- [ ] New functionality is covered by unit tests or integration tests. Code coverage must not decrease.
- [ ] If a bug has been fixed, a new unit test has been written (beforehand) to prove misbehavior
- [ ] There are no new SpotBugs warnings.

## Special notes to reviewer

2024-08-02 09:00 UTC, schwepmo requested changes
LGTM! I left some minor remarks

2024-08-02 10:09 UTC, kschrab commented on rti/mosaic-rti-api/src/main/java/org/eclipse/mosaic/rti/api/federatestarter/JavaFederateExecutor.java
> +    private String createClasspath(String fileSeparator, String pathSeparator) {
> Could there ever be an issue when using the relative paths to the root and lib directories?

What scenario do you think of? I assume that this feature is available in all runtime implementations. It was at least documented in the Java 8 docs: https://docs.oracle.com/javase/8/docs/technotes/tools/windows/classpath.html

2024-08-02 10:26 UTC, schwepmo commented on rti/mosaic-rti-api/src/main/java/org/eclipse/mosaic/rti/api/federatestarter/JavaFederateExecutor.java
>          final String fileSep = host.operatingSystem == CLocalHost.OperatingSystem.WINDOWS ? ";" : ":";
Alright, but shouldn't the same logic apply to the file separator?

2024-08-02 10:33 UTC, kschrab commented on rti/mosaic-rti-api/src/main/java/org/eclipse/mosaic/rti/api/federatestarter/JavaFederateExecutor.java
>          final String fileSep = host.operatingSystem == CLocalHost.OperatingSystem.WINDOWS ? ";" : ":";
🤔 good point

2024-08-02 10:39 UTC, schwepmo commented on rti/mosaic-rti-api/src/main/java/org/eclipse/mosaic/rti/api/federatestarter/JavaFederateExecutor.java
> +    private String createClasspath(String fileSeparator, String pathSeparator) {
Maybe I'm missing something but if MOSAIC is started through e.g., the SimulationRunner couldn't this path be wrong?

2024-08-02 11:45 UTC, kschrab commented on rti/mosaic-rti-api/src/main/java/org/eclipse/mosaic/rti/api/federatestarter/JavaFederateExecutor.java
> +    private String createClasspath(String fileSeparator, String pathSeparator) {
The paths specified here start at the execution directory of the federate, which is set in the `workingDir` variable. This working directory is set to the place where the federate.jar is located. This is either `tmp/federate-id` (only if `deploy=true`) or `bin/fed/federate-id`. The `lib` directory added to the classpath is _not_ the `lib` directory of MOSAIC, but (an optional) `lib` directory inside the federate directory (e.g. inside `bin/fed/federate-id`).

2024-08-02 12:50 UTC, schwepmo commented on rti/mosaic-rti-api/src/main/java/org/eclipse/mosaic/rti/api/federatestarter/JavaFederateExecutor.java
> +    private String createClasspath(String fileSeparator, String pathSeparator) {
Okay, thanks for clarifying. My worry was that with the removed `workingDir` parameter we would loose information. But this seems to have been unfounded!

2024-08-07 12:11 UTC, schwepmo approved these changes

2024-08-07 12:12 UTC, merged