Use List of Connections in CandidateRoute
eclipse/mosaic pull request #86
Opened 2021-04-23 08:39 UTC by kschrab

## Type of this PR 

- [x] Bug fix
- [x] Enhancement

## Description

Previously, CandidateRoute held a list of node Ids which belong to a route. Based on those nodes, a list of connections had been extracted to be used in SUMO. However, this behavior breaks as soon as there are parallel connections with the same start and end node and no nodes in between. Also, the code to generate the list of connections from nodes was very hard to understand.

Now, the CandidateRoute holds a list of connection Ids directly extracted from the edges of its GraphHopper route. Any code which tried to generate the list of connections from node Ids could be eliminated. All tests have been fixed accordingly, now checking for connection Ids instead of node Ids.

## Issue(s) related to this PR

 * Internal Issue 156 
 
## Affected parts of the online documentation

No

## Definition of Done

- [x] You have read CONTRIBUTING.md carefully.
- [x] You have signed the [Contributor License Agreement](http://www.eclipse.org/legal/CLA.php).
- [x] All commits are signed-off (`-s`) with your mail address of your Eclipse Account.
- [x] `origin/main` has been merged into your Fork.
- [x] New functionality is covered by unit tests or integration tests. Code coverage must not decrease.
- [ ] There are no new SpotBugs warnings. 
- [x] Coding guidelines have been observed (see CONTRIBUTING.md).
- [x] All tests pass.

## Special notes to reviewer

2021-04-23 08:40 UTC, kschrab commented
@schwepmo please review :)

2021-04-26 11:36 UTC, schwepmo requested changes
Looks good! I made a few small comments.

2021-04-26 11:41 UTC, kschrab commented on fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/traci/writer/TrafficLightPhaseWriter.java
> -        out.writeDouble(argument.getDuration() / 1000d);
correct :)

2021-04-26 11:45 UTC, kschrab commented on lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/graphhopper/GraphHopperRouting.java
>          return true;
Yes, if there's no explicit connection given in the source position, than it does not matter which the first connection actually is.

2021-04-26 11:47 UTC, kschrab commented on fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/navigation/RoadPositionFactory.java
> +        return refine(new SimpleRoadPosition(Iterables.getLast(currentRouteConnectionIds), laneIndex, -1d, 0d));
Done

2021-04-28 14:17 UTC, rprotzmann approved these changes

2021-04-28 14:18 UTC, merged